version: '3'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./database:/database

  sqlitebrowser:
    image: lscr.io/linuxserver/sqlitebrowser:latest
    container_name: sqlitebrowser
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      # - /path/to/config:/config
      - ./database:/database
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
