version: '3'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "9001:9000"
      - "8081:8080"
    volumes:
      - ./app:/app

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: todo_app
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3360:3306"
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"

volumes:
  db-data:
