use SCA_ITS;

ALTER TABLE Student
ADD
    COLUMN Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
ADD
    COLUMN Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

UPDATE Student SET Created_At = CURRENT_TIMESTAMP();