version: '3'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
      - ./.vscode-server:/root/.vscode-server
      - ./.nuget:/root/.nuget/
    networks:
      - my-network

  db:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: TEST
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: Dev@1234
    ports:
      - 3307:3306
    volumes:
      - ./dbData:/var/lib/mysql
    networks:
      - my-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - my-network

networks:
  my-network:
    name: test-network
