
namespace SCA_ITS_back_end.Models;

public enum PARENT_REGISTRATION_STATUS
{
    ADD_DETAILS = 1,
    ADD_STUDENTS = 2,
    ADD_OTHER_PARENTS = 3,
    ADD_REQUIRED_DOCS = 4,
    PAY_REGISTRATION_FEE = 5,
    APPROVED = 6,
    REJECTED = 7
}