
namespace SCA_ITS_back_end.Models;

public enum STUDENT_REGISTRATION_STATUS
{
    ADD_BASIC_DETAILS = 1,
    ADD_GENERAL_INFO = 2,
    ADD_RELIGIOUS_INFO = 3,
    ADD_SCHOLASTIC_INFO = 4,
    ADD_MEDICAL_DETAILS = 5,
    ADD_MEDICAL_CONDITIONS = 6,
    ADD_OTHER_PARENTS = 7,
    ADD_NON_SCA_STUDENTS = 8,
    ADD_REQUIRED_DOCS = 9,
    OCCUPATIONAL_THERAPY_NEEDED = 10,
    DIAGNOSTIC_TEST_NEEDED = 11,
    APPROVAL_REQUESTED = 12,
    APPROVED = 13,
    REJECTED = 14
}