version: '3'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      - HOST=0.0.0.0
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app

  pocketbase:
    build:
      context: .
      dockerfile: pocketbase.Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - ./pb_migrations:/pocketbase/pb_migrations
      - pb_data:/pocketbase/pb_data

volumes:
  pb_data:
